# List of bird species to scrape for in Xeno-Canto
species_list = [
    "Brant Goose",
    "Red-breasted Goose",
    "Canada Goose",
    "Barnacle Goose",
    "Snow Goose",
    "Greylag Goose",
    "Taiga Bean Goose",
    "Pink-footed Goose",
    "Tundra Bean Goose",
    "Greater White-fronted Goose",
    "Lesser White-fronted Goose",
    "Mute Swan",
    "Bewick's Swan",
    "Whooper Swan",
    "Egyptian Goose",
    "Common Shelduck",
    "Ruddy Shelduck",
    "Mandarin Duck",
    "Garganey",
    "Blue-winged Teal",
    "Northern Shoveler",
    "Gadwall",
    "Eurasian Wigeon",
    "Mallard",
    "Northern Pintail",
    "Eurasian Teal",
    "Green-winged Teal",
    "Marbled Duck",
    "Red-crested Pochard",
    "Common Pochard",
    "Ferruginous Duck",
    "Ring-necked Duck",
    "Tufted Duck",
    "Greater Scaup",
    "Lesser Scaup",
    "Common Eider",
    "Velvet Scoter",
    "Common Scoter",
    "Long-tailed Duck",
    "Common Goldeneye",
    "Smew",
    "Common Merganser",
    "Red-breasted Merganser",
    "Ruddy Duck",
    "White-headed Duck",
    "Hazel Grouse",
    "Rock Ptarmigan",
    "Western Capercaillie",
    "Black Grouse",
    "Grey Partridge",
    "Common Pheasant",
    "Common Quail",
    "Red-legged Partridge",
    "Rock Partridge",
    "European Nightjar",
    "Alpine Swift",
    "Common Swift",
    "Pallid Swift",
    "Great Bustard",
    "Houbara Bustard",
    "Macqueen's Bustard",
    "Little Bustard",
    "Great Spotted Cuckoo",
    "Common Cuckoo",
    "Pallas's Sandgrouse",
    "Feral Pigeon",
    "Stock Dove",
    "Common Wood Pigeon",
    "European Turtle Dove",
    "Oriental Turtle Dove",
    "Eurasian Collared Dove",
    "Water Rail",
    "Corn Crake",
    "Spotted Crake",
    "Common Moorhen",
    "Eurasian Coot",
    "Purple Gallinule",
    "Western Swamphen",
    "Baillon's Crake",
    "Little Crake",
    "Common Crane",
    "Little Grebe",
    "Red-necked Grebe",
    "Great Crested Grebe",
    "Horned Grebe",
    "Black-necked Grebe",
    "Greater Flamingo",
    "Eurasian Stone-curlew",
    "Eurasian Oystercatcher",
    "Black-winged Stilt",
    "Pied Avocet",
    "Northern Lapwing",
    "Sociable Lapwing",
    "European Golden Plover",
    "Pacific Golden Plover",
    "Grey Plover",
    "Common Ringed Plover",
    "Little Ringed Plover",
    "Killdeer",
    "Kentish Plover",
    "Eurasian Dotterel",
    "Eurasian Whimbrel",
    "Slender-billed Curlew",
    "Eurasian Curlew",
    "Bar-tailed Godwit",
    "Black-tailed Godwit",
    "Ruddy Turnstone",
    "Red Knot",
    "Ruff",
    "Broad-billed Sandpiper",
    "Curlew Sandpiper",
    "Temminck's Stint",
    "Sanderling",
    "Dunlin",
    "Purple Sandpiper",
    "Little Stint",
    "White-rumped Sandpiper",
    "Buff-breasted Sandpiper",
    "Pectoral Sandpiper",
    "Western Sandpiper",
    "Eurasian Woodcock",
    "Jack Snipe",
    "Great Snipe",
    "Common Snipe",
    "Terek Sandpiper",
    "Red-necked Phalarope",
    "Red Phalarope",
    "Common Sandpiper",
    "Spotted Sandpiper",
    "Green Sandpiper",
    "Lesser Yellowlegs",
    "Common Redshank",
    "Marsh Sandpiper",
    "Wood Sandpiper",
    "Spotted Redshank",
    "Common Greenshank",
    "Cream-colored Courser",
    "Collared Pratincole",
    "Black-winged Pratincole",
    "Black-legged Kittiwake",
    "Ivory Gull",
    "Sabine's Gull",
    "Slender-billed Gull",
    "Black-headed Gull",
    "Little Gull",
    "Laughing Gull",
    "Franklin's Gull",
    "Audouin's Gull",
    "Mediterranean Gull",
    "Common Gull",
    "Great Black-backed Gull",
    "Glaucous Gull",
    "Iceland Gull",
    "European Herring Gull",
    "Caspian Gull",
    "Yellow-legged Gull",
    "Lesser Black-backed Gull",
    "Gull-billed Tern",
    "Caspian Tern",
    "Lesser Crested Tern",
    "Sandwich Tern",
    "Little Tern",
    "Roseate Tern",
    "Common Tern",
    "Arctic Tern",
    "Whiskered Tern",
    "White-winged Tern",
    "Black Tern",
    "Great Skua",
    "Pomarine Jaeger",
    "Parasitic Jaeger",
    "Long-tailed Jaeger",
    "Common Murre",
    "Long-billed Murrelet",
    "Red-throated Loon",
    "Black-throated Loon",
    "Pacific Loon",
    "Common Loon",
    "Yellow-billed Loon",
    "European Storm Petrel",
    "Leach's Storm Petrel",
    "Band-rumped Storm Petrel",
    "Scopoli's Shearwater",
    "Cory's Shearwater",
    "Sooty Shearwater",
    "Manx Shearwater",
    "Yelkouan Shearwater",
    "Black Stork",
    "White Stork",
    "Northern Gannet",
    "Pygmy Cormorant",
    "Great Cormorant",
    "European Shag",
    "African Sacred Ibis",
    "Glossy Ibis",
    "Eurasian Spoonbill",
    "Eurasian Bittern",
    "Little Bittern",
    "Black-crowned Night Heron",
    "Squacco Heron",
    "Western Cattle Egret",
    "Grey Heron",
    "Purple Heron",
    "Great Egret",
    "Little Egret",
    "Great White Pelican",
    "Pink-backed Pelican",
    "Dalmatian Pelican",
    "Osprey",
    "Black-winged Kite",
    "Bearded Vulture",
    "Egyptian Vulture",
    "European Honey Buzzard",
    "Griffon Vulture",
    "Cinereous Vulture",
    "Short-toed Snake Eagle",
    "Lesser Spotted Eagle",
    "Greater Spotted Eagle",
    "Booted Eagle",
    "Steppe Eagle",
    "Golden Eagle",
    "Bonelli's Eagle",
    "Eurasian Sparrowhawk",
    "Eurasian Goshawk",
    "Western Marsh Harrier",
    "Hen Harrier",
    "Pallid Harrier",
    "Montagu's Harrier",
    "Red Kite",
    "Black Kite",
    "White-tailed Eagle",
    "Rough-legged Buzzard",
    "Long-legged Buzzard",
    "Common Buzzard",
    "Western Barn Owl",
    "Boreal Owl",
    "Little Owl",
    "Northern Hawk-Owl",
    "Eurasian Pygmy Owl",
    "Eurasian Scops Owl",
    "Long-eared Owl",
    "Short-eared Owl",
    "Eurasian Eagle-Owl",
    "Tawny Owl",
    "Eurasian Hoopoe",
    "European Roller",
    "Common Kingfisher",
    "Blue-cheeked Bee-eater",
    "European Bee-eater",
    "Eurasian Wryneck",
    "Eurasian Three-toed Woodpecker",
    "Middle Spotted Woodpecker",
    "Lesser Spotted Woodpecker",
    "Great Spotted Woodpecker",
    "White-backed Woodpecker",
    "Black Woodpecker",
    "European Green Woodpecker",
    "Grey-headed Woodpecker",
    "Lesser Kestrel",
    "Common Kestrel",
    "Red-footed Falcon",
    "Eleonora's Falcon",
    "Merlin",
    "Eurasian Hobby",
    "Saker Falcon",
    "Gyrfalcon",
    "Peregrine Falcon",
    "Eurasian Golden Oriole",
    "Great Grey Shrike",
    "Lesser Grey Shrike",
    "Woodchat Shrike",
    "Red-backed Shrike",
    "Brown Shrike",
    "Long-tailed Shrike",
    "Eurasian Jay",
    "Eurasian Magpie",
    "Spotted Nutcracker",
    "Red-billed Chough",
    "Alpine Chough",
    "Western Jackdaw",
    "Rook",
    "Carrion Crow",
    "Hooded Crow",
    "Northern Raven",
    "Bohemian Waxwing",
    "Coal Tit",
    "Crested Tit",
    "Marsh Tit",
    "Willow Tit",
    "Eurasian Blue Tit",
    "Great Tit",
    "Eurasian Penduline Tit",
    "Bearded Reedling",
    "Woodlark",
    "White-winged Lark",
    "Eurasian Skylark",
    "Crested Lark",
    "Horned Lark",
    "Greater Short-toed Lark",
    "Bimaculated Lark",
    "Calandra Lark",
    "Mediterranean Short-toed Lark",
    "Sand Martin",
    "Eurasian Crag Martin",
    "Barn Swallow",
    "Western House Martin",
    "Red-rumped Swallow",
    "Cetti's Warbler",
    "Long-tailed Tit",
    "Wood Warbler",
    "Western Bonelli's Warbler",
    "Hume's Leaf Warbler",
    "Yellow-browed Warbler",
    "Pallas's Leaf Warbler",
    "Radde's Warbler",
    "Dusky Warbler",
    "Willow Warbler",
    "Common Chiffchaff",
    "Iberian Chiffchaff",
    "Greenish Warbler",
    "Great Reed Warbler",
    "Moustached Warbler",
    "Aquatic Warbler",
    "Sedge Warbler",
    "Paddyfield Warbler",
    "Blyth's Reed Warbler",
    "Common Reed Warbler",
    "Marsh Warbler",
    "Booted Warbler",
    "Melodious Warbler",
    "Icterine Warbler",
    "River Warbler",
    "Savi's Warbler",
    "Common Grasshopper Warbler",
    "Zitting Cisticola",
    "Eurasian Blackcap",
    "Garden Warbler",
    "Barred Warbler",
    "Lesser Whitethroat",
    "Western Orphean Warbler",
    "Sardinian Warbler",
    "Western Subalpine Warbler",
    "Moltoni’s Warbler",
    "Eastern Subalpine Warbler",
    "Common Whitethroat",
    "Spectacled Warbler",
    "Dartford Warbler",
    "Vinous-throated Parrotbill",
    "Common Firecrest",
    "Goldcrest",
    "Eurasian Wren",
    "Eurasian Nuthatch",
    "Wallcreeper",
    "Eurasian Treecreeper",
    "Short-toed Treecreeper",
    "Rosy Starling",
    "Common Starling",
    "Spotless Starling",
    "Siberian Thrush",
    "Song Thrush",
    "Mistle Thrush",
    "Redwing",
    "Common Blackbird",
    "Fieldfare",
    "Ring Ouzel",
    "Rufous-tailed Scrub Robin",
    "Spotted Flycatcher",
    "European Robin",
    "White-throated Robin",
    "Thrush Nightingale",
    "Common Nightingale",
    "Bluethroat",
    "Red-breasted Flycatcher",
    "Semicollared Flycatcher",
    "European Pied Flycatcher",
    "Collared Flycatcher",
    "Black Redstart",
    "Common Redstart",
    "Common Rock Thrush",
    "Blue Rock Thrush",
    "Whinchat",
    "European Stonechat",
    "Northern Wheatear",
    "Isabelline Wheatear",
    "Desert Wheatear",
    "Western Black-eared Wheatear",
    "Eastern Black-eared Wheatear",
    "White-throated Dipper",
    "Rock Sparrow",
    "White-winged Snowfinch",
    "Eurasian Tree Sparrow",
    "Spanish Sparrow",
    "Italian Sparrow",
    "House Sparrow",
    "Alpine Accentor",
    "Dunnock",
    "Western Yellow Wagtail",
    "Citrine Wagtail",
    "Grey Wagtail",
    "White Wagtail",
    "Richard's Pipit",
    "Tawny Pipit",
    "Meadow Pipit",
    "Tree Pipit",
    "Olive-backed Pipit",
    "Red-throated Pipit",
    "Water Pipit",
    "Eurasian Chaffinch",
    "Brambling",
    "Hawfinch",
    "Pine Grosbeak",
    "Eurasian Bullfinch",
    "Trumpeter Finch",
    "Common Rosefinch",
    "European Greenfinch",
    "Twite",
    "Common Linnet",
    "Common Redpoll",
    "Lesser Redpoll",
    "Red Crossbill",
    "European Goldfinch",
    "Citril Finch",
    "European Serin",
    "Eurasian Siskin",
    "Lapland Longspur",
    "Snow Bunting",
    "Corn Bunting",
    "Yellowhammer",
    "Pine Bunting",
    "Rock Bunting",
    "Ortolan Bunting",
    "Cirl Bunting",
    "Little Bunting",
    "Rustic Bunting",
    "Black-headed Bunting",
    "Common Reed Bunting",
    "Song Sparrow",
    "Common Yellowthroat"
]